apiVersion: v1
kind: Service
metadata:
  name: test-rest-service
  namespace: dev
spec:
  ports:
    - name: rr
      port: 8000
      targetPort: rest-port
  selector:
    app: test-rest-service-label
  externalIPs:
    - 192.168.0.10

